name: repository_search
description: repository viewer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  dartz: ^0.10.1
  oauth2: ^2.0.2
  flutter_secure_storage: ^9.0.0
  flash: ^3.0.5+1
  webview_flutter: ^3.0.4
  auto_route: ^7.8.3
  http: ^1.1.0
  bloc: ^8.1.2
  sembast: ^3.5.0+1
  path_provider: ^2.1.1
  path: ^1.8.3
  material_floating_search_bar_2: ^0.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_animated_dialog: ^2.0.1
  loading_indicator: ^3.1.1
  flutter_screenutil: ^5.9.0
  flutter_test:
    sdk: flutter


dev_dependencies:
  test: ^1.21.0
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  mockito: ^5.4.0
  golden_toolkit: ^0.15.0
  image_compare: ^1.1.2
  bloc_test: ^9.1.4
  http_mock_adapter: ^0.6.0
  json_serializable: ^6.7.1




flutter:
  uses-material-design: true



