name: repository_search
description: repository viewer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  dartz: ^0.10.1
  oauth2: ^2.0.2
  flutter_secure_storage: ^9.0.0
  flash: ^3.0.5+1
  webview_flutter: ^3.0.4
  auto_route: ^7.8.3
  http: ^1.1.0
  bloc: ^8.1.2
  sembast: ^3.5.0+1
  path_provider: ^2.1.1
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  test: any
  flutter_lints: ^2.0.0

  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.1


flutter:
  uses-material-design: true



